### PR TITLE
Avoid infinite loop calling svp_release()

### PR DESCRIPTION
**Pull request by pmooney**
We hit a bug in our tests when we rolled back twice to the same savepoint. Although this was our bug we only found out when the test never never completed and used much CPU on a Jenkins box.

### CODE REVIEW

**Comment by ribasushi** [comment]
Thank you for the contribution. Is there a chance you could add a failing-without-this test case to the end of  https://github.com/dbsrgits/dbix-class/blob/master/t/storage/savepoints.t ?

If you do not have time to do this - that is ok: the issue will be eventually resolved either way, but an accompanying test is a hard prerequisite to applying this change.

**Comment by pmooney** [comment]
I was hoping you were not going to say that :)

Give me a day or two and I'll add something.

**Comment by pmooney** [comment]
Test added. On the old code it fails, on the new code if passes.

**Comment by ribasushi** [comment]
This has been applied with a leaner implementation as https://github.com/dbsrgits/dbix-class/commit/7fd61b1fc. The pop is now localised in one spot, and I also removed the alarm-harness, as the test will not be executed on older versions given it is all in one commit.

Thank you for your work!

**Comment by ribasushi** [comment]
ARGH! I didn't wait for the smokes to finish, failures on older sqlite. Will re-push in a bit, and update the commit SHA

**Comment by ribasushi** [comment]
Aight, the correct commit is https://github.com/dbsrgits/dbix-class/commit/f5f0cb1dd ;)

**Comment by ribasushi** [comment]
The position of your test (after another block) managed to uncover and lead to a fix of another bug: https://github.com/dbsrgits/dbix-class/commit/66c817df1, so double-cheers ;)

**Comment by pmooney** [comment]
Glad to be of service :)

The bug in DBIx::Class I fixed highlighted a bug in our own code so it 
was actually quite useful ;)

**Comment by ribasushi** [comment]
The fix is now properly in the CPAN index. Sorry it took so long :/

**Pull request closed without merging**
