### PR TITLE
RT #113741

### PR DESCRIPTION
**Pull request by fgabolde**
@ribasushi I have written a few tests (and also the actual fix, but I haven't committed it yet).

The exception is thrown *after* the deployment occurs, so the first call to deploy() creates the tables, and the second one dies with "A versioned schema has already been deployed, try upgrade instead.". So these tests are not very useful and I'm not sure how to make them better.

I'm sending the PR anyway to have a space in which to converse (this is rather more comfortable than RT), if you have any ideas.

### CODE REVIEW

**Comment by fgabolde** [comment]
(Please don't merge until the issues above are fixed!)

**Comment by ribasushi** [comment]
This is now fixed via https://github.com/dbsrgits/dbix-class/commit/e7dcdf69fd#diff-7ec2db724e80c975475473f856913213.

Thanks for spotting!

**Comment by fgabolde** [comment]
@ribasushi Didn't even think of `:memory:`, nice.

Thanks for the fix!

**Comment by ribasushi** [comment]
The fix is now properly in the CPAN index. Sorry it took so long :/

**Pull request closed without merging**
