### PR TITLE
fix data type comparison in tests

### PR DESCRIPTION
**Pull request by Mic92**
Here are the test failures: https://hydra.nixos.org/build/162237547/nixlog/1

### CODE REVIEW

**Comment by gregoa** [comment]
Here's a different patch (against a different version) which accepts both lower case and upper case /integer/ and should work with older and newer versions of SQLite:
https://salsa.debian.org/perl-team/modules/packages/libdbix-class-perl/-/blob/master/debian/patches/SQLite-3.37.0.patch

**Comment by Mic92** [comment]
Ok, not sure what the debian policy is on upstreaming patches is, but here we go: https://github.com/Perl5/DBIx-Class/pull/142

**Comment by ribasushi** [comment]
Closing in favor of #142 , but also see https://github.com/Perl5/DBIx-Class/pull/142#issuecomment-1016333665

**Comment by gregoa** [comment]
@Mic92: thanks, I was not sure if a new PR or a link to the patch in the existing one is better.
@ribasushi: thanks as well!

**Pull request closed without merging**
